[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
glue = "EVh92BTdvhGSwQ2tx3wgZftuRfsP2oXfEcUmXoSwP9Hd"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
